### ISSUE TITLE
Runtime panic 

### ISSUE THREAD

**Issue by danni-popova** [testcontainers/testcontainers-go#294] opened 2021-03-16 13:21 UTC
**Describe the bug**
Trying to run a test results in a panic when trying to get mapped ports.

**To Reproduce**
https://github.com/todanni/account/blob/main/internal/repository/repository_test.go

**Expected behavior**
Not panic.

** docker info **
output of the command:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 6
  Running: 0
  Paused: 0
  Stopped: 6
 Images: 7
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 25.01GiB
 Name: docker-desktop
 ID: K2UZ:4XFZ:UKRM:UXYT:MSZF:OGA3:QDVU:GVOR:EYU5:54DD:Q3J4:KSCK
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Additional context**
Output from running go test 
```
❯ go test
2021/03/16 13:17:45 Starting container id: dd41a0e8a506 image: quay.io/testcontainers/ryuk:0.2.3
2021/03/16 13:17:46 Waiting for container id dd41a0e8a506 image: quay.io/testcontainers/ryuk:0.2.3
--- FAIL: TestRunAuthenticationTestSuite (0.28s)
    suite.go:63: test panicked: runtime error: index out of range [0] with length 0
        goroutine 6 [running]:
        runtime/debug.Stack(0xc00014e218, 0xc99160, 0xc000128c60)
                /usr/local/go/src/runtime/debug/stack.go:24 +0x9f
        github.com/stretchr/testify/suite.failOnPanic(0xc0001ce780)
                /home/dannipo/go/pkg/mod/github.com/stretchr/testify@v1.7.0/suite/suite.go:63 +0x5b
        panic(0xc99160, 0xc000128c60)
                /usr/local/go/src/runtime/panic.go:965 +0x1b9
        github.com/testcontainers/testcontainers-go.(*DockerContainer).MappedPort(0xc00045e100, 0xddd700, 0xc0005244e0, 0xcede63, 0x8, 0x0, 0x0, 0x3132303200000000, 0x63)
                /home/dannipo/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/docker.go:133 +0x485
        github.com/testcontainers/testcontainers-go/wait.(*HostPortStrategy).WaitUntilReady(0xc00011c600, 0xddd6c8, 0xc0005244e0, 0xddd9a0, 0xc00045e100, 0x0, 0x0)
                /home/dannipo/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/wait/host_port.go:59 +0x16f
        github.com/testcontainers/testcontainers-go.(*DockerContainer).Start(0xc00045e100, 0xddd6c8, 0xc0000360d0, 0x0, 0x0)
                /home/dannipo/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/docker.go:165 +0x315
        github.com/testcontainers/testcontainers-go.(*DockerProvider).RunContainer(0xc0005060f0, 0xddd6c8, 0xc0000360d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd00532, ...)
                /home/dannipo/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/docker.go:727 +0xeb
        github.com/testcontainers/testcontainers-go.NewReaper(0xddd6c8, 0xc0000360d0, 0xc000152180, 0x24, 0xdcd3a0, 0xc0005060f0, 0x0, 0x0, 0x0, 0x0, ...)
                /home/dannipo/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:78 +0x455
        github.com/testcontainers/testcontainers-go.(*DockerProvider).CreateContainer(0xc0005060f0, 0xddd6c8, 0xc0000360d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xcee503, ...)
                /home/dannipo/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/docker.go:534 +0x18c8
        github.com/testcontainers/testcontainers-go.GenericContainer(0xddd6c8, 0xc0000360d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xcee503, 0x8, ...)
                /home/dannipo/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/generic.go:43 +0xb5
        github.com/todanni/authentication/test/container.NewPGContainer(0xcf23fe, 0xf, 0xcea328, 0xcea318, 0xc0000bfd88)
                /mnt/c/Projects/todanni/authentication/test/container/postgres.go:41 +0x3db
        github.com/todanni/authentication/internal/repository.(*AccountRepoTestSuite).SetupSuite(0xc0004385a0)
                /mnt/c/Projects/todanni/authentication/internal/repository/repository_test.go:55 +0x48
        github.com/stretchr/testify/suite.Run(0xc0001ce780, 0xdd4880, 0xc0004385a0)
                /home/dannipo/go/pkg/mod/github.com/stretchr/testify@v1.7.0/suite/suite.go:118 +0x5c7
        github.com/todanni/authentication/internal/repository.TestRunAuthenticationTestSuite(0xc0001ce780)
                /mnt/c/Projects/todanni/authentication/internal/repository/repository_test.go:25 +0x51
        testing.tRunner(0xc0001ce780, 0xd1bd78)
                /usr/local/go/src/testing/testing.go:1194 +0xef
        created by testing.(*T).Run
                /usr/local/go/src/testing/testing.go:1239 +0x2b3
FAIL
exit status 1
FAIL    github.com/todanni/authentication/internal/repository   0.287s
```

**Comment by discoverAnkit** [comment] 2021-03-17 08:08
I am also facing the same issue

**Comment by ikolomiyets** [comment] 2021-03-17 10:39
Incidentally, I've started getting the same issue recently, however it does happen intermittently.

Here is the stacktrace:
```2021/03/17 10:16:42 Starting container id: 7d1eb382f2c7 image: quay.io/testcontainers/ryuk:0.2.3
2021/03/17 10:16:42 Waiting for container id 7d1eb382f2c7 image: quay.io/testcontainers/ryuk:0.2.3
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/testcontainers/testcontainers-go.(*DockerContainer).MappedPort(0xc000040400, 0x1e07d60, 0xc000804660, 0x1c65505, 0x8, 0x0, 0x0, 0xc0000ca6f0, 0x63)
	/Users/ikolomiyets/Development/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.9.0/docker.go:135 +0x471
github.com/testcontainers/testcontainers-go/wait.(*HostPortStrategy).WaitUntilReady(0xc0005ac920, 0x1e07d60, 0xc000804660, 0x1e08060, 0xc000040400, 0x0, 0x0)
	/Users/ikolomiyets/Development/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.9.0/wait/host_port.go:59 +0x166
github.com/testcontainers/testcontainers-go.(*DockerContainer).Start(0xc000040400, 0x1e07d20, 0xc00003a108, 0x0, 0x0)
	/Users/ikolomiyets/Development/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.9.0/docker.go:167 +0x315
github.com/testcontainers/testcontainers-go.(*DockerProvider).RunContainer(0xc0009864b0, 0x1e07d20, 0xc00003a108, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1c7f790, ...)
	/Users/ikolomiyets/Development/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.9.0/docker.go:702 +0xe2
github.com/testcontainers/testcontainers-go.NewReaper(0x1e07d20, 0xc00003a108, 0xc0004e4150, 0x24, 0x1dea480, 0xc0009864b0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/ikolomiyets/Development/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.9.0/reaper.go:78 +0x43f
github.com/testcontainers/testcontainers-go.(*DockerProvider).CreateContainer(0xc0009864b0, 0x1e07d20, 0xc00003a108, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1c9b3a0, ...)
	/Users/ikolomiyets/Development/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.9.0/docker.go:538 +0x1553
github.com/testcontainers/testcontainers-go.GenericContainer(0x1e07d20, 0xc00003a108, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1c9b3a0, 0x4c, ...)
	/Users/ikolomiyets/Development/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.9.0/generic.go:43 +0xb5
github.com/iktech/artifactor.TestMain(0xc000040080)
	/Users/ikolomiyets/work/artifactor/dao_test.go:109 +0x705
main.main()
	_testmain.go:437 +0x165```

I'm not sure after which upgrade exactly it started occurring, but currently I'm using docker version `20.10.5` on laptop.

At the same time this never happens in the pipelines which are running on docker version `19.03.13-ce`.
So, by the looks of it, this might be docker engine related.

A working theory is that perhaps docker changed the way `ContainerInspect` behaves. It might be that before, the function call *always* returned the ports in the array if they were defined in the container specification. Now, by the looks of it, they return ports only when they are already mounted, or whatever lifecycle events they are going through. 
So, it looks like a classical race condition.

I guess somewhere between HostPortStrategy.WaitUntilReady or DockerContainer.MappedPort they should  make the repeated calls to the Docker Engine until the ports appear in the response.

**Comment by discoverAnkit** [comment] 2021-03-17 11:50
@ikolomiyets Interesting catch ..
I downgraded my docker engine to 19.03.12 and now I am not getting that error any more..
However I am getting some other error now..

Here is the stacktrace 

`2021/03/17 17:18:09 Starting container id: eecd577d997d image: quay.io/testcontainers/ryuk:0.2.3
2021/03/17 17:18:10 Waiting for container id eecd577d997d image: quay.io/testcontainers/ryuk:0.2.3
failed to create container: creating reaper failed: could not start container: host port waiting failed: error during connect: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.40/exec/e7371bafc33a42bafb4c6c58603ac68298d2477180dad101c5f4276be21cd7cb/start": net/http: HTTP/1.x transport connection broken: unsupported transfer encoding: "identity"
    suite.go:63: test panicked: runtime error: invalid memory address or nil pointer dereference
        goroutine 13 [running]:
        runtime/debug.Stack(0xc0001a1650, 0x1bbae80, 0x2518f40)
        	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
        github.com/stretchr/testify/suite.failOnPanic(0xc0004e6900)
        	/Users/ankitgoyal/go/src/github.com/sixt/com.sixt.service.crm-search/vendor/github.com/stretchr/testify/suite/suite.go:63 +0x57
        panic(0x1bbae80, 0x2518f40)
        	/usr/local/go/src/runtime/panic.go:969 +0x1b9
        github.com/sixt/com.sixt.service.crm-search/testutils.(*ElasticsearchTestHelper).StartEsContainer(0xc000136ce0, 0x1d2d985, 0x4, 0x1d2d989, 0x4, 0x8808998)
        	/Users/ankitgoyal/go/src/github.com/sixt/com.sixt.service.crm-search/testutils/elasticsearch.go:87 +0x4ed
        github.com/sixt/com.sixt.service.crm-search/repository_test.(*EventHandlerTestSuite).SetupSuite(0xc0004dccc0)
        	/Users/ankitgoyal/go/src/github.com/sixt/com.sixt.service.crm-search/repository/ElasticSearchRepository_test.go:37 +0x7d
        github.com/stretchr/testify/suite.Run(0xc0004e6900, 0x1e5e3c0, 0xc0004dccc0)
        	/Users/ankitgoyal/go/src/github.com/sixt/com.sixt.service.crm-search/vendor/github.com/stretchr/testify/suite/suite.go:118 +0x5d6
        github.com/sixt/com.sixt.service.crm-search/repository_test.TestEventHandlerTestSuite(0xc0004e6900)
        	/Users/ankitgoyal/go/src/github.com/sixt/com.sixt.service.crm-search/repository/ElasticSearchRepository_test.go:32 +0x51
        testing.tRunner(0xc0004e6900, 0x1d70ad0)
        	/usr/local/go/src/testing/testing.go:1123 +0xef
        created by testing.(*T).Run
        	/usr/local/go/src/testing/testing.go:1168 +0x2b3
--- FAIL: TestEventHandlerTestSuite (20.81s)
FAIL

Process finished with exit code 1
`

**Comment by maxim-nazarenko** [comment] 2021-03-17 20:51
Some findings which may help.

[this call](https://github.com/moby/moby/blob/master/client/container_inspect.go#L18) to the Docker engine API returns not populated ports mapping `27017/tcp: []` (I am using MondoDB in my tests)
I updated the code to have 5 retries and it always stops after first one with populated ports mapping.
Container state with zero-len ports mapping and populated mapping looks the same:

No port mapping
`container state is: created=2021-03-17T20:30:50.4160845Z, state=&types.ContainerState{Status:"running", Running:true, Paused:false, Restarting:false, OOMKilled:false, Dead:false, Pid:24504, ExitCode:0, Error:"", StartedAt:"2021-03-17T20:30:50.8475111Z", FinishedAt:"0001-01-01T00:00:00Z", Health:(*types.Health)(nil)}`

Populated port mapping
`container state is: created=2021-03-17T20:30:50.4160845Z, state=&types.ContainerState{Status:"running", Running:true, Paused:false, Restarting:false, OOMKilled:false, Dead:false, Pid:24504, ExitCode:0, Error:"", StartedAt:"2021-03-17T20:30:50.8475111Z", FinishedAt:"0001-01-01T00:00:00Z", Health:(*types.Health)(nil)}`

**Comment by maxim-nazarenko** [comment] 2021-03-23 22:20
Since this issue is kind of blocker for me, this [commit](https://github.com/maxim-nazarenko/testcontainers-go/commit/5d30355e35cef7ea59ecb96d812a698f0de7ed5e) in forked repository introduces retry logic for `DockerContainer.Ports()` function which is used by `DockerContainer.MappedPorts()`.
I am not considering this approach as production-ready, because I assume that the root cause is in the `DockerContainer.inspectContainer()` with its caching but removing caching is pretty tough step on high loads.

**Comment by sazzer** [comment] 2021-03-28 17:40
I'm getting this on Docker 20.10.5 on macOS 10.15.7, and it's a complete blocker for me.

```
-> % docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 117
  Running: 34
  Paused: 0
  Stopped: 83
 Images: 988
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.121-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.942GiB
 Name: docker-desktop
 ID: XAIX:FISD:2CQD:6ZGR:TIJV:4J54:AAKU:RMLU:33FB:UUJH:SSGX:32UR
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 154
  Goroutines: 132
  System Time: 2021-03-28T17:33:18.4880674Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

The only way I've found past it - short of downgrading Docker, which I've not yet tried - is to remove the `wait.ForListeningPort` and add in an explicit pause. `time.Sleep(6 * time.Second)` *seems* to make it work every time, though 5 seconds turned out to not always be enough. Obviously a 6 second pause in every single integration tests is quite a bit cost though :(

**Comment by butuzov** [comment] 2021-04-02 05:48
Issue has gone since after #295, waiting for release. 
Meanwhile, you can test it with the cloned master branch and replace directive

**Comment by Jesse-Cameron** [comment] 2021-04-14 00:47
I managed to pull the fix in with:
`go get -v "github.com/testcontainers/testcontainers-go@54854fb15ccb5162fe673bac4b2522e5f84de9a0"`

Looking forward to the next release :)

**Comment by IliaBulavintsev** [comment] 2021-04-28 18:59
any updates Guys?

**Comment by 1stDMann** [comment] 2021-05-13 11:10
Hmm, with `go get -v "github.com/testcontainers/testcontainers-go@54854fb15ccb5162fe673bac4b2522e5f84de9a0"` I get the error
```
2021/05/13 13:05:00 Starting container id: dde02ef6b853 image: quay.io/testcontainers/ryuk:0.2.3
2021/05/13 13:05:01 Waiting for container id dde02ef6b853 image: quay.io/testcontainers/ryuk:0.2.3
2021/05/13 13:05:01 Container is ready id: dde02ef6b853 image: quay.io/testcontainers/ryuk:0.2.3
2021/05/13 13:05:01 Starting container id: 1d77c49ca4ed image: nginx
2021/05/13 13:05:01 Waiting for container id 1d77c49ca4ed image: nginx
2021/05/13 13:05:01 Container is ready id: 1d77c49ca4ed image: nginx
--- FAIL: TestMyNginxLatestReturn (2.51s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0xcacf1c]

goroutine 19 [running]:
testing.tRunner.func1.2(0xd20840, 0x112d210)
	C:/Program Files/Go/src/testing/testing.go:1143 +0x345
```
with `Docker 20.10.6` (and `go 1.16.4`) on Windows.
#

**Comment by xtreding** [comment] 2021-05-27 16:00
Same issue. Are you going to fix it?

**Comment by mniak** [comment] 2021-05-27 16:47
I could workaround this by installing the merge commit of the PR #295 mentioned by @butuzov.

```
go get github.com/testcontainers/testcontainers-go@54854fb15ccb5162fe673bac4b2522e5f84de9a0
```

**Comment by xtreding** [comment] 2021-06-03 16:45
v0.11.0 has fixed this issue!

**Comment by mdelapenya** [comment] 2021-06-10 08:38
I think we can close this one, as it seems fixed. Please reopen if you still see it, thanks!

**Closed by mdelapenya** 2021-06-10 08:38 UTC
