### ISSUE TITLE
go get github.com/testcontainers/testcontainers-go cannot find errdefs module

### ISSUE THREAD

**Issue by codefromthecrypt** [testcontainers/testcontainers-go#302] opened 2021-03-28 00:00 UTC
**Describe the bug**

go get github.com/testcontainers/testcontainers-go cannot find errdefs module

**To Reproduce**
```
$ go get github.com/testcontainers/testcontainers-go
go: downloading github.com/testcontainers/testcontainers-go v0.10.0
go: downloading github.com/containerd/continuity v0.0.0-20201208142359-180525291bb7
github.com/testcontainers/testcontainers-go imports
	github.com/docker/docker/errdefs: cannot find module providing package github.com/docker/docker/errdefs
go: downloading github.com/cenkalti/backoff v1.1.0
```

**Expected behavior**
No errors

** go info **
output of the command:

```
$ go version
go version go1.16.2 darwin/amd64
```

**Comment by mdelapenya** [comment] 2022-05-19 08:04
Hey @codefromthecrypt I'm not able to reproduce this yet:

```
$ cd /tmp
mdelapenya at Manuels-MacBook-Pro in /tmp
$ mkdir gooo
mdelapenya at Manuels-MacBook-Pro in /tmp
$ cd gooo/
mdelapenya at Manuels-MacBook-Pro in /tmp/gooo
$ eval "$(gvm 1.16.2)"
mdelapenya at Manuels-MacBook-Pro in /tmp/gooo
$ go get github.com/testcontainers/testcontainers-go
mdelapenya at Manuels-MacBook-Pro in /tmp/gooo
$ go version
go version go1.16.2 darwin/amd64
mdelapenya at Manuels-MacBook-Pro in /tmp/gooo
```

If you agree, I'd close this issue as no longer reproducible

**Closed** 2022-05-19 15:23 UTC
