### ISSUE TITLE
[Bug]: Can't update this dependency

### ISSUE THREAD

**Issue by MCWertGaming** [testcontainers/testcontainers-go#687] opened 2022-12-11 19:49 UTC
### Testcontainers version

v0.15.0

### Using the latest Testcontainers version?

No

### Host OS

Linux

### Host arch

x86_64

### Go version

1.19.3

### Docker version

```shell
Client:
 Version:           20.10.20
 API version:       1.41
 Go version:        go1.19.2
 Git commit:        9fdeb9c
 Built:             Fri Oct 21 02:23:32 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.20
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.2
  Git commit:       03df974
  Built:            Fri Oct 21 02:23:32 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.10
  GitCommit:        
 runc:
  Version:          1.1.4
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:
```

### Docker info

```shell
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 11
  Running: 1
  Paused: 0
  Stopped: 10
 Images: 93
 Server Version: 20.10.20
 Storage Driver: btrfs
  Build Version: Btrfs v5.18
  Library Version: 102
 Logging Driver: journald
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: /usr/libexec/docker/docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  seccomp
   Profile: default
  selinux
  cgroupns
 Kernel Version: 6.0.10-300.fc37.x86_64
 Operating System: Fedora Linux 37 (Workstation Edition)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 11.06GiB
 Name: damons-fedora
 ID: CPQB:S667:KZNR:LKCN:S5TL:7SJ3:4QUV:C2HP:37JR:S2UC:ZS3E:ZOUO
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true
```

### What happened?

I wanted to update this dependency in a project and it failed because it couldn't find another one. See the output below:

### Relevant log output

```shell
~$ go get github.com/testcontainers/testcontainers-go
github.com/testcontainers/testcontainers-go imports
        github.com/docker/compose/v2/pkg/compose imports
        github.com/docker/docker/builder/remotecontext/urlutil: cannot find module providing package github.com/docker/docker/builder/remotecontext/urlutil
```

**Comment by ramseyjiang** [comment] 2022-12-12 09:23
I met the same bug, it does not work. testcontainers always is the red words

**Comment by mdelapenya** [comment] 2022-12-12 10:19
@MCWertGaming sorry for the inconveniences in updating to the latest 0.16.0 release. Did you read the release notes for that specific issue with the upstream dependencies? The issue with those dependencies is disclosed there, so you need to add some replace directives. It's also documented in the docs: https://golang.testcontainers.org/quickstart/gotest/

On the other hand, I'd like to highlight this discussion: https://github.com/testcontainers/testcontainers-go/discussions/653

@ramseyjiang , I'm really interested in 
> testcontainers always is the red words

What are your main pain points or concerns? I'd appreciate your constructive feedback to help you trust

**Comment by mdelapenya** [comment] 2022-12-15 04:59
I'm closing this issue as a duplicate of #634, let's use that one in case we need to comment there, thanks!

@ramseyjiang I'd like to know more on your concerns, so please feel free to use #634 (or open a Discussion) to comment anything you consider

**Closed by mdelapenya** 2022-12-15 04:59 UTC
Labels: bug
