### ISSUE TITLE
[Bug]: Localstack slow to start with test containers

### ISSUE THREAD

**Issue by Sovietaced** [testcontainers/testcontainers-go#1495] opened 2023-08-10 17:40 UTC
### Testcontainers version

v0.22.0

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host arch

x86

### Go version

go version go1.20.5 linux/amd64

### Docker version

```shell
Client: Docker Engine - Community
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996
 Built:             Fri Jul 21 20:35:18 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.6
  Git commit:       a61e2b4
  Built:            Fri Jul 21 20:35:18 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker info

```shell
Client: Docker Engine - Community
 Version:    24.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.5
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.18.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 8
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.19.0-1029-aws
 Operating System: Ubuntu 22.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 30.99GiB
 Name: U-2AQ9340S9KI77
 ID: 70a46a18-0dbf-4c5f-a753-a45e3b27a0f2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: sovietaced
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### What happened?

When using testcontainers to start localstack on my Linux box, local stack will fail to become ready in time. Logs from the container show the following.

```
$ docker logs cd57f2030e8c -f

LocalStack version: 2.2.1.dev
LocalStack Docker container id: cd57f2030e8c
LocalStack build date: 2023-08-09
LocalStack build git hash: 78f635ad

2023-08-10T16:49:00.536  WARN --- [  MainThread] localstack.deprecations    : EDGE_PORT is deprecated (since 2.0.0) and will be removed in upcoming releases of LocalStack! This configuration will be migrated to GATEWAY_LISTEN
2023-08-10T16:49:15.483  INFO --- [  MainThread] localstack.utils.bootstrap : Execution of "start_runtime_components" took 14743.62ms
Unexpected exception while starting infrastructure: gave up waiting for edge server on 0.0.0.0:4566 Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 395, in start_infra
    thread = do_start_infra(asynchronous, apis, is_in_docker)
  File "/opt/code/localstack/localstack/services/infra.py", line 487, in do_start_infra
    thread = start_runtime_components()
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 73, in wrapped
    return f(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/infra.py", line 480, in start_runtime_components
    raise TimeoutError(
TimeoutError: gave up waiting for edge server on 0.0.0.0:4566
```

After following some of the guidance from this [GitHub issue](https://github.com/localstack/localstack/issues/4840) I am able to get localstack to startup in 45 seconds when using testcontainers with the following environment variable: "SKIP_SSL_CERT_DOWNLOAD": "1".

However I am not able to reproduce problem in two different situations. 
1) When running docker natively (without testcontainers) on my Linux machine
2) When running testcontainers on my Mac

So the issue seems to be isolated to testcontainers on my Linux machine. I have tried with many different localstack images and it is not related to the localstack image.

Based on the workaround, it appears to be related to internet access specifically when the container is running under testcontainers. I just don't know much about how testcontainers works related to networking. 

### Relevant log output

```shell
Localstack takes 45 seconds to start only when using testcontainers. It only succeeds in starting if I pass the following environment variable: "SKIP_SSL_CERT_DOWNLOAD": "1"


$ go test
2023/08/10 10:16:12 github.com/testcontainers/testcontainers-go - Connected to docker: 
  Server Version: 24.0.5
  API Version: 1.43
  Operating System: Ubuntu 22.04.2 LTS
  Total Memory: 31738 MB
2023/08/10 10:16:12 🐳 Creating container for image docker.io/testcontainers/ryuk:0.5.1
2023/08/10 10:16:12 ✅ Container created: f9b0d90ad707
2023/08/10 10:16:12 🐳 Starting container: f9b0d90ad707
2023/08/10 10:16:13 ✅ Container started: f9b0d90ad707
2023/08/10 10:16:13 🚧 Waiting for container id f9b0d90ad707 image: docker.io/testcontainers/ryuk:0.5.1. Waiting for: &{Port:8080/tcp timeout:<nil> PollInterval:100ms}
Setting LOCALSTACK_HOST to localhost (to match host-routable address for container)
2023/08/10 10:16:13 🐳 Creating container for image localstack/localstack:latest
2023/08/10 10:16:13 ✅ Container created: 64d08e8ea947
2023/08/10 10:16:13 🐳 Starting container: 64d08e8ea947
2023/08/10 10:16:13 ✅ Container started: 64d08e8ea947
2023/08/10 10:16:13 🚧 Waiting for container id 64d08e8ea947 image: localstack/localstack:latest. Waiting for: &{timeout:0xc000460328 Port:4566/tcp Path:/_localstack/health StatusCodeMatcher:0x884680 ResponseMatcher:0x9556c0 UseTLS:false AllowInsecure:false TLSConfig:<nil> Method:GET Body:<nil> PollInterval:100ms UserInfo:}
2023/08/10 10:16:58 container running
2023/08/10 10:16:58 &{0xc00013b6b0}
PASS
ok      gitlab.com/<redacted>/kits/mq/sqs        45.504s
```
```


### Additional information

_No response_

**Comment by mdelapenya** [comment] 2023-08-10 23:04
Thanks @Sovietaced for opening this issue. I'd like to understand better how you create the localstack container: using a generic container o our Go module for localstack?

**Comment by Sovietaced** [comment] 2023-08-10 23:14
> Thanks @Sovietaced for opening this issue. I'd like to understand better how you create the localstack container: using a generic container o our Go module for localstack?

Using the go module and trying to follow the docs. 

```
func setupLocalstack(t *testing.T, ctx context.Context) *localstack.LocalStackContainer {
	t.Helper()
	container, err := localstack.StartContainer(
		ctx,
		localstack.OverrideContainerRequest(testcontainers.ContainerRequest{
			Image: "localstack/localstack:2.2.0",
			Env: map[string]string{
				"AWS_DEFAULT_REGION":    "us-east-1",
				// We are only testing against SQS
				"SERVICES":              "sqs",
				// This seems to be required on Linux machine for some reason. Otherwise container startup times out.
				"SKIP_SSL_CERT_DOWNLOAD": "1",
			},
		}),
	)

	require.NoError(t, err)
	return container
}
```

**Comment by mdelapenya** [comment] 2023-08-29 11:38
I've talked to the localstack folks to understand better this issue. Will ping you here with their response

**Comment by whummer** [comment] 2023-08-31 08:57
Hey @Sovietaced @mdelapenya , thanks for bringing this to our attention. Turns out this was a slowness caused by some DNS lookups performed on LocalStack startup under certain circumstances. 

We have now pushed a fix which is available in the `localstack/localstack:latest` Docker image. Can you please give that a try and let us know if it works? Thanks! The fix will be included in the next patch/minor release, which we're planning to roll out in the upcoming weeks. 👍

**Comment by Sovietaced** [comment] 2023-08-31 15:53
> Hey @Sovietaced @mdelapenya , thanks for bringing this to our attention. Turns out this was a slowness caused by some DNS lookups performed on LocalStack startup under certain circumstances.
> 
> We have now pushed a fix which is available in the `localstack/localstack:latest` Docker image. Can you please give that a try and let us know if it works? Thanks! The fix will be included in the next patch/minor release, which we're planning to roll out in the upcoming weeks. 👍

Can confirm that I no longer see a long startup delay on `latest`. Thank you!

**Closed** 2023-08-31 15:55 UTC
Labels: bug
