### ISSUE TITLE
HostPortStrategy is flaky - panics when under load

### ISSUE THREAD

**Issue by tigerquoll** [testcontainers/testcontainers-go#315] opened 2021-04-28 12:04 UTC
**Describe the bug**
Wait strategies that rely on a port being available are flaky when multiple test cases are being run.
using v0.10.0 with standard alpine Postgres containers.
```
--- FAIL: DemoTest (0.41s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 5 [running]:
testing.tRunner.func1.1(0x5440080, 0xc0008a6300)
	/usr/local/Cellar/go/1.15.6/libexec/src/testing/testing.go:1072 +0x30d
testing.tRunner.func1(0xc000702c00)
	/usr/local/Cellar/go/1.15.6/libexec/src/testing/testing.go:1075 +0x41a
panic(0x5440080, 0xc0008a6300)
	/usr/local/Cellar/go/1.15.6/libexec/src/runtime/panic.go:969 +0x1b9
github.com/testcontainers/testcontainers-go.(*DockerContainer).MappedPort(0xc000882000, 0x573f8a0, 0xc0000aed80, 0x552ad3d, 0x8, 0x0, 0x0, 0xc0000f4760, 0x63)
	/Users/dale/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/docker.go:133 +0x471
github.com/testcontainers/testcontainers-go/wait.(*HostPortStrategy).WaitUntilReady(0xc0009109e0, 0x573f8a0, 0xc0000aed80, 0x573fb20, 0xc000882000, 0x0, 0x0)
	/Users/dale/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/wait/host_port.go:59 +0x166
github.com/testcontainers/testcontainers-go.(*DockerContainer).Start(0xc000882000, 0x573f8e0, 0xc000696ba0, 0x0, 0x0)
	/Users/dale/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/docker.go:165 +0x315
github.com/testcontainers/testcontainers-go.(*DockerProvider).RunContainer(0xc000696ed0, 0x573f8e0, 0xc000696ba0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x554ff25, ...)
	/Users/dale/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/docker.go:727 +0xe2
```

**To Reproduce**
Can you write a unit test to reproduce your issue?
Reliably crashes with about 12 test cases in a file for me

**Expected behavior**
No panics

** docker info **
output of the command:

```
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 4
  Running: 0
  Paused: 0
  Stopped: 4
 Images: 21
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.121-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 11.7GiB
 Name: docker-desktop
 ID: C4VF:3V5M:2QRC:OP5S:FNKA:4NYN:2AKI:IKWA:52RO:5JCL:XHQO:G3PQ
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 41
  Goroutines: 46
  System Time: 2021-04-28T12:00:12.1737744Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

**Additional context**

**Comment by iamricard** [comment] 2021-04-28 16:59
Pretty sure this is a duplicate of #294

**Comment by mdelapenya** [comment] 2022-05-19 08:33
@tigerquoll could you double check if this is fixed so that we can close the issue?

Besides, if you are able to share a repro snippet, that would be wonderful for us to identify the root cause better.

**Comment by tigerquoll** [comment] 2022-05-26 02:50
v0.11.0 has fixed this issue - thanks

**Closed** 2022-05-26 02:51 UTC
