### ISSUE TITLE
How to mount a directory?

### ISSUE THREAD

**Issue by softshipper** [testcontainers/testcontainers-go#186] opened 2020-04-20 15:05 UTC
Hi all 

I would like to bind a directory to to container and have tried as follow: 

```
path, err := os.Getwd()
assert.NoError(t, err, err)

data := fmt.Sprintf("%s%s", path, "/gogs/data")

//Start gogs container
ctx := context.Background()
req := testcontainer.ContainerRequest{
  Image:        "gogs/gogs:0.11.91",
  ExposedPorts: []string{"3000/tcp"},
  WaitingFor:   wait.ForHTTP("/").WithPort("3000/tcp"),
  BindMounts:   map[string]string{data: "/data"},
  Name:         "gogs",
}

gogs, err := testcontainer.GenericContainer(ctx, testcontainer.GenericContainerRequest{
  ContainerRequest: req,
  Started:          true,
})
```  
It does not bind. What I am trying to achieve is:  

`docker run --rm -it -p 3000:3000 --name=gogs --mount type=bind,source=`pwd`/gogs/data,target=/data gogs/gogs`
 
What am I doing wrong?   

Thanks

**Comment by gianarb** [comment] 2020-04-26 13:28
Hello @softshipper

I tried to double-check your problem and I am not able to reproduce your issue. What do you get as `err` here:

```go
gogs, err := testcontainer.GenericContainer(ctx, testcontainer.GenericContainerRequest{
  ContainerRequest: req,
  Started:          true,
})
``` 

In my case, everything works as expected only if the directory already exists, so you have to check and validate if `data` is there or the process will error.

When the directory exists I do not get any issue and I see the data created from `gogs` in the mounted directory in my laptop

If you are able to reproduce the error please past it here with information such as:

```
docker system info
```

and your go version

Thanks a lot

**Comment by gianarb** [comment] 2020-04-26 13:29
Hello @softshipper

I tried to double-check your problem and I am not able to reproduce your issue. What do you get as `err` here:

```go
gogs, err := testcontainer.GenericContainer(ctx, testcontainer.GenericContainerRequest{
  ContainerRequest: req,
  Started:          true,
})
``` 

In my case, everything works as expected only if the directory already exists, so you have to check and validate if `data` is there or the process will error.

When the directory exists I do not get any issue and I see the data created from `gogs` in the mounted directory in my laptop

If you are able to reproduce the error please past it here with information such as:

```
docker system info
```

and your go version

Thanks a lot

**Comment by gianarb** [comment] 2020-05-06 18:39
Closing for now, feel free to reopen if needed

**Closed by gianarb** 2020-05-06 18:39 UTC
