### ISSUE TITLE
[Bug]: cannot install testcontainers

### ISSUE THREAD

**Issue by reshef-axiom** [testcontainers/testcontainers-go#669] opened 2022-12-06 10:28 UTC
### Testcontainers version

latest

### Using the latest Testcontainers version?

Yes

### Host OS

macos

### Host arch

arm

### Go version

1.18.2

### Docker version

```shell
20.10.12
```

### Docker info

```shell
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1)
  compose: Docker Compose (Docker Inc., v2.2.3)
  scan: Docker Scan (Docker Inc., v0.16.0)

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 72
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: ikkvswqrb7t5su8xukh4yqjxt
  Is Manager: true
  ClusterID: xyid11dwimzl9zrpki0yvmiex
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.65.3
  Manager Addresses:
   192.168.65.3:2377
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 11.68GiB
 Name: docker-desktop
 ID: V6B5:EHMQ:DS76:EZZG:SN46:FPWZ:66LX:RBWK:33BY:URNJ:2BPJ:BO6H
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### What happened?

can't install the library

### Relevant log output

```shell
go get github.com/testcontainers/testcontainers-go

panic: internal error: can't find reason for requirement on github.com/moby/sys/mountinfo@v0.6.0

goroutine 1 [running]:
cmd/go/internal/modget.(*resolver).updateBuildList.func1({{0x14000b437e0?, 0x140016bbab8?}, {0x14000aae416?, 0x1400168a968?}})
        /usr/local/go/src/cmd/go/internal/modget/get.go:1760 +0xf8
cmd/go/internal/modget.(*resolver).updateBuildList(0x140001eae00, {0x10488b7c0, 0x1400002c090}, {0x14000b74420, 0x1, 0x1})
        /usr/local/go/src/cmd/go/internal/modget/get.go:1765 +0x460
cmd/go/internal/modget.(*resolver).applyUpgrades(0x140001eae00, {0x10488b7c0, 0x1400002c090}, {0x140019a5140?, 0x1?, 0x1048713e0?})
        /usr/local/go/src/cmd/go/internal/modget/get.go:1312 +0xc4
cmd/go/internal/modget.runGet({0x10488b7c0, 0x1400002c090}, 0x14000026390?, {0x140000201d0, 0x1, 0x1})
        /usr/local/go/src/cmd/go/internal/modget/get.go:351 +0x3c8
main.invoke(0x104b59b40, {0x140000201c0, 0x2, 0x2})
        /usr/local/go/src/cmd/go/main.go:218 +0x2b0
main.main()
        /usr/local/go/src/cmd/go/main.go:175 +0x770
```

**Comment by mdelapenya** [comment] 2022-12-06 11:02
Hi @reshef-axiom did you check the install instructions in the website https://golang.testcontainers.org/quickstart/gotest?

**Comment by ehansen31** [comment] 2022-12-09 19:07
experiencing the same issue when trying to install via `go get github.com/testcontainers/testcontainers-go`

**Comment by ehrktia** [comment] 2022-12-14 16:27
> 

thank you @ehansen31 the `v0.15.0` worked fine for me as well.

**Comment by mdelapenya** [comment] 2022-12-15 04:58
I'm closing this issue as a duplicate of #634, let's use that one in case we need to comment there, thanks!

**Closed by mdelapenya** 2022-12-15 04:58 UTC
Labels: bug
