### ISSUE TITLE
Opened PR: Contributing Docs need an update based on error logs

### ISSUE THREAD

**Issue by shashank-g172** [testcontainers/testcontainers-go#260] opened 2020-10-26 13:39 UTC
**Describe the bug**
While attempting to build the container locally while adding a new feature, I noticed that that the contributing.md doc needs an update to a later version of go, but I'm not sure how that'll break Travis builds.

**To Reproduce**
Run the steps on the docs once exec'd into the container

**Expected behavior**
No build errors

** docker info **
Command> go vet ./...
output of the command:
/root/go/pkg/mod/github.com/containerd/containerd@v1.4.1/errdefs/errors.go:92:9: undefined: "github.com/pkg/errors".Is
# github.com/testcontainers/testcontainers-go/wait
wait/http.go:154:3: unknown field 'ForceAttemptHTTP2' in struct literal of type http.Transport
wait/http.go:185:16: undefined: http.NewRequestWithContext
note: module requires Go 1.13# github.com/docker/docker/pkg/archive
/root/go/pkg/mod/github.com/docker/docker@v17.12.0-ce-rc1.0.20200916142827-bd33bbf0497b+incompatible/pkg/archive/archive_linux.go:155:18: undefined: strings.ReplaceAll
/root/go/pkg/mod/github.com/docker/docker@v17.12.0-ce-rc1.0.20200916142827-bd33bbf0497b+incompatible/pkg/archive/archive_linux.go:242:18: undefined: strings.ReplaceAll
# github.com/testcontainers/testcontainers-go/wait [github.com/testcontainers/testcontainers-go/wait.test]
wait/http.go:154:3: unknown field 'ForceAttemptHTTP2' in struct literal of type http.Transport
wait/http.go:185:16: undefined: http.NewRequestWithContext

```
$ docker info
docker --version
Docker version 18.06.1-ce, build e68fc7a

```

**Additional context**

**Comment by mdelapenya** [comment] 2022-08-25 08:04
@shashank-g172 I'm still not able to reproduce this is issue, so I'm closing it now.

Please feel free to reopen it if you are still seeing what's described here

Thanks!

**Closed by mdelapenya** 2022-08-25 08:04 UTC
